spring.application.name=Einkaufsliste

# die DB einkaufsliste wird im Benutzerordner des Servers abgelegt
spring.datasource.url = jdbc:h2:file:~/einkaufsliste
spring.datasource.username = sa
spring.datasource.password = geheim

# h2 Console ist unter /h2-console verfügbar
spring.h2.console.enabled = true

# Spring soll die DB-Tabellen automatisch bauen und updaten
spring.jpa.hibernate.ddl-auto: update
