spring.application.name = Einkaufsliste

spring.datasource.url = jdbc:h2:file:./data
spring.datasource.username = tomasz
spring.datasource.password = geheim123

# Automatisches Erzeugen von Datenbank-Tabellen
spring.jpa.hibernate.ddl-auto = update

# SQL Anzeigen
spring.jpa.show-sql = true

# Webbasierter Client für die H2 Datenbank
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console